schema_version = "1.0.0"

id = "restart"
name = "Restart"
version = "1.0.2"
tagline = "Restart Blender"
maintainer = "JR3DFUL"
type = "add-on"

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

tags = ["System"]
